name: Demo Script Action
description: A demo for an action with custom script

branding:
  icon: "activity"
  color: green

runs:
  using: "composite"
  steps:
    - name: Test Custom Script
      shell: bash   
      run: |
        chmod +x ./custom-script.sh
        ${{ github.action_path }}/custom-script.sh
