name: Release and Tag Management

on:
  release:
    types: [published]

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get major version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          MAJOR_VERSION=v${VERSION%%.*}
          echo "major_version=${MAJOR_VERSION}" >> $GITHUB_OUTPUT
          echo "full_version=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Update major version tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -fa ${{ steps.get_version.outputs.major_version }} -m "Update major version tag to ${{ steps.get_version.outputs.full_version }}"
          git push origin ${{ steps.get_version.outputs.major_version }} --force